=== wealthy-laughing-duck/duck-raml/schemas/income-collection.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "categoryId": {
        "type": "integer"
      },
      "amount": {
        "type": "number"
      },
      "description": {
        "type": "string"
      },
      "createdAt": {
        "type": "string"
      },
      "createdBy": {
        "type": "integer"
      }
    },
    "required": [
      "id",
      "categoryId",
      "amount",
      "description",
      "createdAt",
      "createdBy"
    ]
  }
}

=== wealthy-laughing-duck/duck-raml/samples/incomes.json
[
  {
    "id": 1,
    "categoryId": 35,
    "amount": 5462.84,
    "description": "selling first singles",
    "createdAt": "1961-08-10 00:00:00",
    "createdBy": 13
  },
  {
    "id": 2,
    "categoryId": 36,
    "amount": 346.82,
    "description": "first audio recording profit",
    "createdAt": "1957-02-21 00:00:00",
    "createdBy": 14
  },
  {
    "id": 3,
    "categoryId": 37,
    "amount": 8934.61,
    "description": "Sgt. Peppers charity meeting",
    "createdAt": "1967-08-10 00:00:00",
    "createdBy": 13
  }
]
